name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on:  windows-latest
    steps: 
      - name: Print greeting
        run: |
            echo "First output"
            echo "Second output"
      - name: Say Goodbay
        run: echo "Good bay guys..!"
