name: First workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubantu-latest
    steps: 
      - name: Print greeting
        run: echo "Hello world"
      - name: Say Goodbay
        run: echo "Good bay guys..!"
